#!/usr/bin/python

assets_map = {
    'ABCB10F': 'ABCB10',
    'AURE3F': 'AURE3',
    'EGIE3F': 'EGIE3',
    'ENAT3F': 'ENAT3',
    'EQTL3F': 'EQTL3',
    'FLRY3F': 'FLRY3',
    'GOAU4F': 'GOAU4',
    'GGBR4F': 'GGBR4',
    'ITUB4F': 'ITUB4',
    'JBSS3F': 'JBSS3',
    'LREN3F': 'LREN3',
    'MELK3F': 'MELK3',
    'PORT3F': 'PORT3',
    'PSSA3F': 'PSSA3',
    'PETR4F': 'PETR4',
    'RECV3F': 'RECV3',
    'SUZB3F': 'SUZB3',
    'SMTO3F': 'SMTO3',
    'TIMS3F': 'TIMS3',
    'TAEE11F': 'TAEE11',
    'VALE3F': 'VALE3',
    'VIVT3F': 'VIVT3',
}