version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
  
  producer:
    container_name: rabbit-poc-producer
    build:
      context: ./producer/
    depends_on:
        - rabbitmq
    environment:
        AMQP_URL: 'amqp://rabbitmq?connection_attempts=10&retry_delay=10'
  
  consumer-debit:
    container_name: rabbit-poc-debit-consumer
    build:
      context: ./consumer/
    depends_on:
        - rabbitmq
        - producer
    environment:
        AMQP_URL: 'amqp://rabbitmq?connection_attempts=10&retry_delay=10'
        TRANSACTION_TYPE: 'DEBIT'

  consumer-credit:
    container_name: rabbit-poc-credit-consumer
    build:
      context: ./consumer/
    depends_on:
        - rabbitmq
        - producer
    environment:
        AMQP_URL: 'amqp://rabbitmq?connection_attempts=10&retry_delay=10'
        TRANSACTION_TYPE: 'CREDIT'

networks:
  default:
    driver: bridge
